name: Build WSAToolBox with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Java (required by Gradle/Kotlin)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. Grant execute permission for gradlew
      # This is a crucial step to allow the workflow to run the Gradle wrapper
      - name: Make gradlew executable
        run: chmod +x ./WSAToolbox/gradlew

      # 4. Build the project with Gradle
      # This command tells Gradle to run the 'build' task
      - name: Build with Gradle
        run: ./WSAToolbox/gradlew -p ./WSAToolbox build

      # 5. (Optional) Upload the built JAR as an artifact
      # The JAR will be located in the build/libs directory
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: wsatoolbox-jar
          path: WSAToolbox/build/libs/WSAToolbox-1.0-SNAPSHOT.jar
