name: Build WSAToolbox

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest  # Using Windows for native DLL/EXE compatibility

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Kotlin compiler
      run: choco install kotlinc

    - name: Create output directory
      run: mkdir output

    - name: Compile Kotlin to JAR (including runtime)
      working-directory: ./WSAToolbox
      run: |
        kotlinc src/main/kevin -include-runtime -d ../output/WSAToolbox.jar
        # Include all .kt files recursively
        # -include-runtime bundles Kotlin stdlib

    - name: Package resources with JAR
      working-directory: ./WSAToolbox
      run: |
        # Copy all resources to output directory
        xcopy /E /Y src/main\resources ..\output\resources\
        # Create a zip containing both JAR and resources
        cd ..\output
        7z a -tzip WSAToolbox.zip .\*
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: WSAToolbox
        path: output/WSAToolbox.zip
